var cities = ["Abilene",
"Akron", 
"Albuquerque", 
"Amarillo", 
"Ames", 
"Ann Arbor", 
"Asheville, NC", 
"Athens", 
"Atlanta", 
"Augusta", 
"Austin", 
"Bakersfield", 
"Baltimore", 
"Baton Rouge", 
"Beaumont", 
"Bellingham", 
"Birmingham, AL", 
"Boise", 
"Boston", 
"Bowling Green, KY", 
"Burlington", 
"Central Atlantic Coast, FL", 
"Champaign", 
"Charleston, SC", 
"Charlotte", 
"Charlottesville-Harrisonburg", 
"Chattanooga", 
"Chicago", 
"Cincinnati", 
"Cleveland", 
"Coeur D'Alene", 
"College Station", 
"Columbia, MO", 
"Columbia, SC", 
"Columbus", 
"Connecticut", 
"Corpus Christi", 
"Dallas-Fort Worth", 
"Dayton", 
"Delaware", 
"Denver", 
"Des Moines", 
"Detroit", 
"Eastern Idaho", 
"Eastern North Carolina", 
"Edmonton", 
"El Paso", 
"Erie", 
"Fargo", 
"Fayetteville, AR", 
"Fayetteville, NC", 
"Flagstaff", 
"Flint", 
"Florida Keys", 
"Fort Myers-Naples", 
"Fort Wayne", 
"Fresno", 
"Gainesville", 
"Georgia Coast", 
"Grand Rapids", 
"Greater Maine", 
"Greater Maryland", 
"Green Bay", 
"Greenville, SC", 
"Guadalajara", 
"Hamilton", 
"Hampton Roads", 
"Harrisburg", 
"Honolulu", 
"Houston", 
"Indianapolis", 
"Inland Empire", 
"Jackson", 
"Jacksonville", 
"Kalamazoo", 
"Kansas City", 
"Killeen", 
"Kingston", 
"Kitchener-Waterloo", 
"Knoxville", 
"Lafayette, LA", 
"Lancaster, PA", 
"Lansing", 
"Las Cruces", 
"Las Vegas", 
"Lawrence", 
"Lehigh Valley", 
"Leon", 
"Lexington", 
"Lincoln", 
"Little Rock", 
"London, Ont", 
"Los Angeles", 
"Louisville", 
"Lubbock", 
"Madison", 
"Manhattan", 
"Maui", 
"Memphis", 
"Mexico City", 
"Miami", 
"Midland-Odessa", 
"Milwaukee", 
"Minneapolis - St. Paul", 
"Mobile, AL", 
"Modesto", 
"Monterrey", 
"Montreal", 
"Myrtle Beach", 
"NW Indiana", 
"Nashville", 
"New Hampshire", 
"New Jersey", 
"New Jersey (Shore)", 
"New Orleans", 
"New York City", 
"Niagara Region", 
"Ocala, FL", 
"Oklahoma City", 
"Omaha", 
"Orange County", 
"Orlando", 
"Ottawa", 
"Outer Banks, NC", 
"Oxford", 
"Palm Springs", 
"Pensacola, FL", 
"Peoria & Bloomington-Normal", 
"Philadelphia", 
"Phoenix", 
"Piedmont Triad, NC", 
"Pittsburgh", 
"Portland", 
"Portland, ME", 
"Puebla", 
"Quad Cities", 
"Quebec City", 
"Queretaro", 
"Raleigh-Durham", 
"Reading, PA", 
"Reno", 
"Rhode Island", 
"Richmond", 
"Roanoke-Blacksburg", 
"Rockford", 
"Sacramento", 
"Salt Lake City", 
"San Antonio", 
"San Diego", 
"San Francisco Bay Area", 
"San Luis Obispo", 
"Santa Barbara", 
"Santa Fe", 
"Sarasota", 
"Savannah-Hilton Head", 
"Seattle", 
"South Bend", 
"Spokane", 
"Springfield, IL", 
"St Louis", 
"State College", 
"Stillwater", 
"Tacoma", 
"Tallahassee", 
"Tampa Bay", 
"Taos", 
"Tijuana", 
"Toledo", 
"Toluca", 
"Topeka", 
"Toronto", 
"Tucson", 
"Tulsa", 
"Tuscaloosa", 
"Vancouver, WA", 
"Ventura", 
"Waco", 
"Washington D.C.", 
"Western MA", 
"Wichita", 
"Wilkes-Barre Scranton", 
"Wilmington, NC", 
"Windsor", 
"Worcester", 
"Yuma", 
"the Hamptons", 
"Barranquilla", 
"Belo Horizonte", 
"Bogotá", 
"Brasilia", 
"Bucaramanga", 
"Cali - Colombia", 
"Campinas", 
"Cartagena", 
"Cucuta", 
"Goiania", 
"Ibagué", 
"Lima", 
"Medellín", 
"Montevideo", 
"Panama, Panama", 
"Porto Alegre", 
"Rio De Janeiro", 
"San Jose, Costa Rica", 
"Santiago", 
"Santo Domingo", 
"São Paulo", 
"Villavicencio", 
"Amsterdam", 
"Athens, GR", 
"Basel", 
"Belfast", 
"Berlin", 
"Birmingham, UK", 
"Bordeaux", 
"Bratislava", 
"Bristol", 
"Brussels", 
"Bucharest", 
"Budapest", 
"Copenhagen", 
"Dublin", 
"Edinburgh", 
"Ekaterinburg", 
"Florence", 
"Geneva", 
"Genoa", 
"Glasgow", 
"Gothenburg", 
"Helsinki", 
"Istanbul", 
"Kazan", 
"Krakow", 
"Lausanne", 
"Leeds", 
"Lille", 
"Lisbon", 
"London", 
"Lyon", 
"Manchester", 
"Marseille", 
"Merseyside", 
"Milan", 
"Minsk", 
"Moscow", 
"Munich", 
"Nantes", 
"Newcastle", 
"Nice", 
"Novosibirsk", 
"Oslo", 
"Paris", 
"Porto", 
"Portsmouth", 
"Poznan", 
"Prague", 
"Rome", 
"Rostov-On-Don", 
"Rotterdam", 
"Saint Petersburg", 
"Sheffield", 
"Sochi", 
"Sofia", 
"Stockholm", 
"Strasbourg", 
"Tallinn", 
"Toulouse", 
"Trojmiasto", 
"Vienna", 
"Vilnius", 
"Warsaw", 
"Wroclaw", 
"Zagreb", 
"Zurich", 
"Middle East", 
"Abu Dhabi", 
"Amman", 
"Baku", 
"Beirut", 
"Doha", 
"Dubai", 
"Eastern Province, KSA", 
"Jeddah", 
"Manama", 
"Riyadh", 
"Tel Aviv", 
"Alexandria", 
"Cairo", 
"Cape Town", 
"Casablanca", 
"Durban", 
"Johannesburg", 
"Lagos", 
"Nairobi", 
"Port Elizabeth", 
"Beijing", 
"Changsha", 
"Chengdu", 
"Chongqing", 
"Dalian", 
"Foshan", 
"Guangzhou", 
"Guiyang", 
"Hangzhou", 
"Hong Kong", 
"Incheon", 
"Jinan", 
"Macau", 
"Nanjing", 
"Ningbo", 
"Qingdao", 
"Seoul", 
"Shanghai", 
"Shenzhen", 
"Suzhou", 
"Taichung", 
"Taipei", 
"Tianjin", 
"Tokyo", 
"Wuhan", 
"Xi'An", 
"Xiamen", 
"Yantai", 
"South Asia", 
"Ahmedabad", 
"Ajmer", 
"Bangalore", 
"Bhubaneswar", 
"Chandigarh", 
"Chennai", 
"Coimbatore", 
"Colombo", 
"Guwahati", 
"Hyderabad", 
"Indore", 
"Jaipur", 
"Jodhpur", 
"Kochi", 
"Kolkata", 
"Mangalore", 
"Mumbai", 
"Mysore", 
"Nagpur", 
"Nashik", 
"New Delhi", 
"Pune", 
"Surat", 
"Thiruvananthapuram", 
"Udaipur", 
"Vadodara", 
"Visakhapatnam", 
"Bali", 
"Bandung", 
"Bangkok", 
"Cebu", 
"Hanoi", 
"Ho Chi Minh City", 
"Ipoh", 
"Jakarta", 
"Johor Bahru", 
"Kuala Lumpur", 
"Manila", 
"Penang", 
"Singapore", 
"Surabaya", 
"Adelaide", 
"Auckland", 
"Brisbane", 
"Canberra", 
"Geelong", 
"Gold Coast", 
"Melbourne", 
"Mornington Peninsula", 
"Perth", 
"Sunshine Coast", 
"Sydney", 
"Wellington"];